export const LLAMADA_API = 'LLAMADA_API';
export const QUITAR_LOADER = 'QUITAR_LOADER';
export const INICIAR_SESION = 'INICIAR_SESION';
export const CERRAR_SESION = 'CERRAR_SESION';
export const INICIO_SESION_EXITOSO = 'INICIO_SESION_EXITOSO';
export const TOKEN_VALIDO = 'TOKEN_VALIDO';
export const FALLO_INICIO_SESION = 'FALLO_INICIO_SESION';

export const LISTA_DE_RENOVACIONES_EXITOSO = 'LISTA_DE_RENOVACIONES_EXITOSO'
export const LISTA_DE_RENOVACIONES_ENCERO = 'LISTA_DE_RENOVACIONES_ENCERO'
export const LISTA_DE_RENOVACIONES_FALLO = 'LISTA_DE_RENOVACIONES_FALLO'
export const LLAMADA_API_RENOVACIONES = 'LLAMADA_API_RENOVACIONES';

export const LISTA_SOLICITUDES_ENCERO = 'LISTA_SOLICITUDES_ENCERO'
export const LISTA_SOLICITUDES_EXITOSO = 'LISTA_SOLICITUDES_EXITOSO'
export const LISTA_SOLICITUDES_FALLO = 'LISTA_SOLICITUDES_FALLO'
export const LLAMADA_API_SOLICITUDES = 'LLAMADA_API_SOLICITUDES';